### PR TITLE
update read speeds when using the properties - fix #2

### LINKED ISSUE #2: Limit reads & cache values
***NOTE*** This issue by @ATMakersBill transferred from original repo.

It looks like there's code to read the i2c bus and keep the results for future calls to joystick, acceleration, and buttons.  However, the button code doesn't seem to update the buffer.

It looks like it would be possible to make fewer reads and improve performance.  Here's my suggestion....

1. Add an optional parameter to the init() that takes a maxAge parameter (default to .1sec?). 
2. In __read_data() keep track of whether it's been over maxAge since the last read.  If not use the current buffer.  If you do a read, update the last read time
3. If maxAge is set to zero, then it would always fetch on every read.
4. If maxAge is set to -1 then the data read calls would never call read_data: the user would need to call a public method (read_data()?) to fetch the data.

I think that would give full control to the clients of the library.

### PR DESCRIPTION
**Pull request by jfurcean**
This commit should help with the issue raised in #2. You should notice improved performance using the `examples/nunchuk_analog_mouse.py` example.

### CODE REVIEW

**Comment by caternuson** [comment]
Look at the approach I've pushed here:
https://github.com/caternuson/Adafruit_CircuitPython_Nunchuk/tree/speedup

The `nunchuk_analog_mouse.py` example has also been changed to demonstrate how the new approach would be used.

**Comment by jfurcean** [comment]
You asked to separate the issue out, so I was trying to fix the data read issue first. I don't think there is an issue with the property method once the data read issue is solved, which I believe the proposed method in this PR solves that. I think the your proposed approach will still cause the slowness in the data read if a user uses `nunchuck.button_c` throughout their code instead of unpacking the tuple at the top of their while loop. I think they should be able to use the `nunchuck.button_c` through out their code.

Have you tested the two versions of the code with the original `examples/nunchuk_analog_mouse.py`? 

Here is mine with the Classic Controller as well. https://github.com/jfurcean/CircuitPython_WiiChuck

It seems to me to be much cleaner without the values property and the tuple unpacking

**Comment by caternuson** [comment]
Yep, thanks for making this new PR. Here we are just focused on the slowness issue. The current library definitely has issues with that.

I did try the mouse example with the existing library, your PR, and the version I linked above. The current library is slow. Your PR is noticeably faster. Same for the version I linked. The version I linked is an example that takes the approach suggested here:
https://github.com/adafruit/Adafruit_CircuitPython_Nunchuk/pull/17#issuecomment-761725600

While your PR does improve the performance relative to the existing library, it introduces new issues. Consider this simple example:
```python
import board
import adafruit_nunchuk

nc = adafruit_nunchuk.Nunchuk(board.I2C())

while True:
    print(nc.joystick)
```
Using your PR code, it behaves like this:
```
(202, 58)
(202, 58)
(202, 58)
(202, 58)
(202, 58)
(197, 44)
(197, 44)
(197, 44)
(133, 35)
(133, 35)
(133, 35)
(133, 35)
(129, 47)
(129, 47)
(129, 47)
(129, 47)
(129, 47)
(129, 47)
```
Yes it is faster. But it returns lots of duplicate data. For the analog mouse example, that generally doesn't matter, since it doesn't show up in any noticeable way. But that behavior could be an issue for other use cases.

Using the version of the code I linked above, it behaves like this:
```
(225, 126)
(212, 93)
(206, 35)
(80, 53)
(59, 59)
(57, 59)
(56, 59)
(50, 69)
(49, 191)
(201, 207)
(202, 206)
(203, 205)
(207, 205)
(209, 203)
(217, 196)
(230, 146)
(231, 136)
(228, 132)
```
Which is the more expected behavior.

I think it will be overly complex to provide *both* property access and speed and make it happen automagically. More logic would be needed to prevent the behavior shown above. Another option might be to have a manual `update` function that users would be required to call to actually update the buffer contents. The properties just return the current buffer contents. That would look something like:
```python
while True:
    nc.update()
    x, y = nc.joystick
    if nc.button_C:
        print("button C pressed")
    # etc
```
Needing to call `update()` is a bit clunky, but the code after that could use the familiar property access.

**Comment by jfurcean** [comment]
I am not sure I agree about that the 'duplicate data' is an issue. This same things happens with buttons in any circuit python code. I think this actually producing what is expected. Individuals using the libraries would need to handle the issue just like the c and z buttons are handled. The last approach is exactly how the Arduino library handles it and I believe it will end up producing the same results as this PR. I agree that it is clunky though and why I didn't suggest it.

[edit] I think the update() approach might be the best solution.

**Comment by dglaude** [comment]
There might be an issue with the use of time.monotonic() as in CircuitPython, with some MCU, the precision of that function change over time... https://learn.adafruit.com/clue-sensor-plotter-circuitpython/time-in-circuitpython
Maybe for mouse usage, this will become a problem.
Not that I have a solution.

**Comment by jfurcean** [comment]
Yeah, the update() method is probably the best current solution. This will align with the similar Arduino library as well.

**Pull request closed without merging**
